### ISSUE TITLE
New Designs [epic]

### ISSUE THREAD

**Issue by curran** [vizhub-core/vzcode#445]
We have new designs from professional UI designer Sam Vogt!

![Image](https://github.com/vizhub-core/vzcode/assets/68416/6f325273-08f9-4390-97be-63a70cd0981d)

Overall:

 * [x] #446

Sidebar:

 * [x] #463
 * [x] #464
 * [x] #465
 * [x] #466
 * [x] Move Settings button to the top of the sidebar
 * [x] Add text "Project Files"
 * [x] Add horizontal rule
 * [x] New icon for Settings (gear)
 * [x] New icon for New File (paper with plus)
 * [x] Add icons per file type next to files

Tabs:

 * [x] Use new X icon
 * [x] Iterate style (tab size, border radius, padding, font, color)
 * [x] Iterate style for non-tab background

![Image](https://github.com/vizhub-core/vzcode/assets/68416/173824ce-d21f-4924-95d5-1632b05c7e2d)

 * [x] Implement hover state

![Image](https://github.com/vizhub-core/vzcode/assets/68416/204fb41e-aca5-4ae2-84d8-8ae6b7a8554b)

For the bottom portion:

 * #456
